version: "3.8"
networks:
  Prom-net:
    driver: bridge
services:
  server:
    image: "infracloudio/csvserver:latest"
    container_name: csvserver
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    volumes:
      - ~/inputFile:/csvserver/inputdata
    networks:
      - Prom-net
  prometheus:
    image: "prom/prometheus:v2.22.0"
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - Prom-net
